/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum ProcessStatus {
    Starting = "starting",
    Running = "running",
    Draining = "draining",
    Stopping = "stopping",
    Stopped = "stopped",
    Failed = "failed",
}

/** @internal */
export const ProcessStatus$ = z.nativeEnum(ProcessStatus);
