/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type CreateLobbyDeprecatedSecurity = {
    playerAuth: string;
};

export type CreateLobbyDeprecatedRequest = {
    createLobbyParams: components.CreateLobbyParams;
    appId?: string | undefined;
    roomId?: string | undefined;
};

export type CreateLobbyDeprecatedResponse = {
    httpMeta: components.HTTPMetadata;
    lobby?: components.Lobby | undefined;
};

/** @internal */
export namespace CreateLobbyDeprecatedSecurity$ {
    export type Inbound = {
        playerAuth: string;
    };

    export const inboundSchema: z.ZodType<CreateLobbyDeprecatedSecurity, z.ZodTypeDef, Inbound> = z
        .object({
            playerAuth: z.string(),
        })
        .transform((v) => {
            return {
                playerAuth: v.playerAuth,
            };
        });

    export type Outbound = {
        playerAuth: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyDeprecatedSecurity> =
        z
            .object({
                playerAuth: z.string(),
            })
            .transform((v) => {
                return {
                    playerAuth: v.playerAuth,
                };
            });
}

/** @internal */
export namespace CreateLobbyDeprecatedRequest$ {
    export type Inbound = {
        CreateLobbyParams: components.CreateLobbyParams$.Inbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<CreateLobbyDeprecatedRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CreateLobbyParams: components.CreateLobbyParams$.inboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => {
            return {
                createLobbyParams: v.CreateLobbyParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.roomId === undefined ? null : { roomId: v.roomId }),
            };
        });

    export type Outbound = {
        CreateLobbyParams: components.CreateLobbyParams$.Outbound;
        appId?: string | undefined;
        roomId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyDeprecatedRequest> = z
        .object({
            createLobbyParams: components.CreateLobbyParams$.outboundSchema,
            appId: z.string().optional(),
            roomId: z.string().optional(),
        })
        .transform((v) => {
            return {
                CreateLobbyParams: v.createLobbyParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.roomId === undefined ? null : { roomId: v.roomId }),
            };
        });
}

/** @internal */
export namespace CreateLobbyDeprecatedResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Lobby?: components.Lobby$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateLobbyDeprecatedResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Lobby: components.Lobby$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Lobby === undefined ? null : { lobby: v.Lobby }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Lobby?: components.Lobby$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateLobbyDeprecatedResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                lobby: components.Lobby$.outboundSchema.optional(),
            })
            .transform((v) => {
                return {
                    HttpMeta: v.httpMeta,
                    ...(v.lobby === undefined ? null : { Lobby: v.lobby }),
                };
            });
}
