/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type CreatePrivateLobbyDeprecatedSecurity = {
    playerAuth: string;
};

export type CreatePrivateLobbyDeprecatedRequest = {
    appId?: string | undefined;
    region?: components.Region | undefined;
    local?: boolean | undefined;
};

export type CreatePrivateLobbyDeprecatedResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    roomId?: string | undefined;
};

/** @internal */
export namespace CreatePrivateLobbyDeprecatedSecurity$ {
    export type Inbound = {
        playerAuth: string;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedSecurity,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            playerAuth: z.string(),
        })
        .transform((v) => {
            return {
                playerAuth: v.playerAuth,
            };
        });

    export type Outbound = {
        playerAuth: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedSecurity
    > = z
        .object({
            playerAuth: z.string(),
        })
        .transform((v) => {
            return {
                playerAuth: v.playerAuth,
            };
        });
}

/** @internal */
export namespace CreatePrivateLobbyDeprecatedRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        region?: components.Region | undefined;
        local?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            appId: z.string().optional(),
            region: components.Region$.optional(),
            local: z.boolean().default(false),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
                local: v.local,
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        region?: components.Region | undefined;
        local: boolean;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedRequest
    > = z
        .object({
            appId: z.string().optional(),
            region: components.Region$.optional(),
            local: z.boolean().default(false),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
                local: v.local,
            };
        });
}

/** @internal */
export namespace CreatePrivateLobbyDeprecatedResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        RoomId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            RoomId: z.string().optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.RoomId === undefined ? null : { roomId: v.RoomId }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        RoomId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            roomId: z.string().optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.roomId === undefined ? null : { RoomId: v.roomId }),
            };
        });
}
