/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetBuildInfoRequest = {
    buildId: number;
    appId?: string | undefined;
};

export type GetBuildInfoResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    build?: components.Build | undefined;
};

/** @internal */
export namespace GetBuildInfoRequest$ {
    export type Inbound = {
        buildId: number;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetBuildInfoRequest, z.ZodTypeDef, Inbound> = z
        .object({
            buildId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                buildId: v.buildId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        buildId: number;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBuildInfoRequest> = z
        .object({
            buildId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                buildId: v.buildId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace GetBuildInfoResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Build?: components.Build$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetBuildInfoResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Build: components.Build$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Build === undefined ? null : { build: v.Build }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Build?: components.Build$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBuildInfoResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            build: components.Build$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.build === undefined ? null : { Build: v.build }),
            };
        });
}
