/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetDeploymentInfoRequest = {
    deploymentId: number;
    appId?: string | undefined;
};

export type GetDeploymentInfoResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    deployment?: components.Deployment | undefined;
};

/** @internal */
export namespace GetDeploymentInfoRequest$ {
    export type Inbound = {
        deploymentId: number;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetDeploymentInfoRequest, z.ZodTypeDef, Inbound> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        deploymentId: number;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDeploymentInfoRequest> = z
        .object({
            deploymentId: z.number().int(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                deploymentId: v.deploymentId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace GetDeploymentInfoResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Deployment?: components.Deployment$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetDeploymentInfoResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Deployment: components.Deployment$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Deployment === undefined ? null : { deployment: v.Deployment }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Deployment?: components.Deployment$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDeploymentInfoResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            deployment: components.Deployment$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.deployment === undefined ? null : { Deployment: v.deployment }),
            };
        });
}
