/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetLogsForProcessRequest = {
    processId: string;
    appId?: string | undefined;
    follow?: boolean | undefined;
    tailLines?: number | undefined;
};

export type GetLogsForProcessResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    res?: string | undefined;
};

/** @internal */
export namespace GetLogsForProcessRequest$ {
    export type Inbound = {
        processId: string;
        appId?: string | undefined;
        follow?: boolean | undefined;
        tailLines?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForProcessRequest, z.ZodTypeDef, Inbound> = z
        .object({
            processId: z.string(),
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                processId: v.processId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
            };
        });

    export type Outbound = {
        processId: string;
        appId?: string | undefined;
        follow: boolean;
        tailLines: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForProcessRequest> = z
        .object({
            processId: z.string(),
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                processId: v.processId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                tailLines: v.tailLines,
            };
        });
}

/** @internal */
export namespace GetLogsForProcessResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        res?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForProcessResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            res: z.string().optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        res?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForProcessResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            res: z.string().optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });
}
