/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetProcessInfoDeprecatedRequest = {
    processId: string;
    appId?: string | undefined;
};

export type GetProcessInfoDeprecatedResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    process?: components.Process | undefined;
};

/** @internal */
export namespace GetProcessInfoDeprecatedRequest$ {
    export type Inbound = {
        processId: string;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetProcessInfoDeprecatedRequest, z.ZodTypeDef, Inbound> =
        z
            .object({
                processId: z.string(),
                appId: z.string().optional(),
            })
            .transform((v) => {
                return {
                    processId: v.processId,
                    ...(v.appId === undefined ? null : { appId: v.appId }),
                };
            });

    export type Outbound = {
        processId: string;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetProcessInfoDeprecatedRequest
    > = z
        .object({
            processId: z.string(),
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                processId: v.processId,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace GetProcessInfoDeprecatedResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Process?: components.Process$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetProcessInfoDeprecatedResponse, z.ZodTypeDef, Inbound> =
        z
            .object({
                HttpMeta: components.HTTPMetadata$.inboundSchema,
                Process: components.Process$.inboundSchema.optional(),
            })
            .transform((v) => {
                return {
                    httpMeta: v.HttpMeta,
                    ...(v.Process === undefined ? null : { process: v.Process }),
                };
            });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Process?: components.Process$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetProcessInfoDeprecatedResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            process: components.Process$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.process === undefined ? null : { Process: v.process }),
            };
        });
}
