/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetPaymentMethodResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    paymentMethod?: components.PaymentMethod | undefined;
};

/** @internal */
export namespace GetPaymentMethodResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        PaymentMethod?: components.PaymentMethod$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetPaymentMethodResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PaymentMethod: components.PaymentMethod$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.PaymentMethod === undefined ? null : { paymentMethod: v.PaymentMethod }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PaymentMethod?: components.PaymentMethod$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPaymentMethodResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            paymentMethod: components.PaymentMethod$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.paymentMethod === undefined ? null : { PaymentMethod: v.paymentMethod }),
            };
        });
}
