/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetRunningProcessesRequest = {
    appId?: string | undefined;
    region?: components.Region | undefined;
};

export type GetRunningProcessesResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    processWithRooms?: Array<components.ProcessWithRooms> | undefined;
};

/** @internal */
export namespace GetRunningProcessesRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        region?: components.Region | undefined;
    };

    export const inboundSchema: z.ZodType<GetRunningProcessesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            region: components.Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        region?: components.Region | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRunningProcessesRequest> = z
        .object({
            appId: z.string().optional(),
            region: components.Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });
}

/** @internal */
export namespace GetRunningProcessesResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        ProcessWithRooms?: Array<components.ProcessWithRooms$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<GetRunningProcessesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            ProcessWithRooms: z.array(components.ProcessWithRooms$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.ProcessWithRooms === undefined
                    ? null
                    : { processWithRooms: v.ProcessWithRooms }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        ProcessWithRooms?: Array<components.ProcessWithRooms$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRunningProcessesResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            processWithRooms: z.array(components.ProcessWithRooms$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.processWithRooms === undefined
                    ? null
                    : { ProcessWithRooms: v.processWithRooms }),
            };
        });
}
