/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type LoginGoogleRequest = {
    loginGoogleRequest: components.LoginGoogleRequest;
    appId?: string | undefined;
};

export type LoginGoogleResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    loginResponse?: components.LoginResponse | undefined;
};

/** @internal */
export namespace LoginGoogleRequest$ {
    export type Inbound = {
        LoginGoogleRequest: components.LoginGoogleRequest$.Inbound;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<LoginGoogleRequest, z.ZodTypeDef, Inbound> = z
        .object({
            LoginGoogleRequest: components.LoginGoogleRequest$.inboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                loginGoogleRequest: v.LoginGoogleRequest,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        LoginGoogleRequest: components.LoginGoogleRequest$.Outbound;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LoginGoogleRequest> = z
        .object({
            loginGoogleRequest: components.LoginGoogleRequest$.outboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                LoginGoogleRequest: v.loginGoogleRequest,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace LoginGoogleResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        LoginResponse?: components.LoginResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<LoginGoogleResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            LoginResponse: components.LoginResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.LoginResponse === undefined ? null : { loginResponse: v.LoginResponse }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        LoginResponse?: components.LoginResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, LoginGoogleResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            loginResponse: components.LoginResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.loginResponse === undefined ? null : { LoginResponse: v.loginResponse }),
            };
        });
}
