/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type SetLobbyStateRequest = {
    roomId: string;
    setLobbyStateParams: components.SetLobbyStateParams;
    appId?: string | undefined;
};

export type SetLobbyStateResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    lobby?: components.Lobby | undefined;
};

/** @internal */
export namespace SetLobbyStateRequest$ {
    export type Inbound = {
        roomId: string;
        SetLobbyStateParams: components.SetLobbyStateParams$.Inbound;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<SetLobbyStateRequest, z.ZodTypeDef, Inbound> = z
        .object({
            roomId: z.string(),
            SetLobbyStateParams: components.SetLobbyStateParams$.inboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                roomId: v.roomId,
                setLobbyStateParams: v.SetLobbyStateParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        roomId: string;
        SetLobbyStateParams: components.SetLobbyStateParams$.Outbound;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetLobbyStateRequest> = z
        .object({
            roomId: z.string(),
            setLobbyStateParams: components.SetLobbyStateParams$.outboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                roomId: v.roomId,
                SetLobbyStateParams: v.setLobbyStateParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace SetLobbyStateResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Lobby?: components.Lobby$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<SetLobbyStateResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Lobby: components.Lobby$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Lobby === undefined ? null : { lobby: v.Lobby }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Lobby?: components.Lobby$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SetLobbyStateResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            lobby: components.Lobby$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.lobby === undefined ? null : { Lobby: v.lobby }),
            };
        });
}
