/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type UpdateRoomConfigRequest = {
    roomId: string;
    updateRoomConfigParams: components.UpdateRoomConfigParams;
    appId?: string | undefined;
};

export type UpdateRoomConfigResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace UpdateRoomConfigRequest$ {
    export type Inbound = {
        roomId: string;
        UpdateRoomConfigParams: components.UpdateRoomConfigParams$.Inbound;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateRoomConfigRequest, z.ZodTypeDef, Inbound> = z
        .object({
            roomId: z.string(),
            UpdateRoomConfigParams: components.UpdateRoomConfigParams$.inboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                roomId: v.roomId,
                updateRoomConfigParams: v.UpdateRoomConfigParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        roomId: string;
        UpdateRoomConfigParams: components.UpdateRoomConfigParams$.Outbound;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateRoomConfigRequest> = z
        .object({
            roomId: z.string(),
            updateRoomConfigParams: components.UpdateRoomConfigParams$.outboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                roomId: v.roomId,
                UpdateRoomConfigParams: v.updateRoomConfigParams,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace UpdateRoomConfigResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
    };

    export const inboundSchema: z.ZodType<UpdateRoomConfigResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateRoomConfigResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
            };
        });
}
