/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type UpdateAppRequest = {
    appConfig: components.AppConfig;
    appId?: string | undefined;
};

export type UpdateAppResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Ok
     */
    application?: components.Application | undefined;
};

/** @internal */
export namespace UpdateAppRequest$ {
    export type Inbound = {
        AppConfig: components.AppConfig$.Inbound;
        appId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateAppRequest, z.ZodTypeDef, Inbound> = z
        .object({
            AppConfig: components.AppConfig$.inboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                appConfig: v.AppConfig,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });

    export type Outbound = {
        AppConfig: components.AppConfig$.Outbound;
        appId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateAppRequest> = z
        .object({
            appConfig: components.AppConfig$.outboundSchema,
            appId: z.string().optional(),
        })
        .transform((v) => {
            return {
                AppConfig: v.appConfig,
                ...(v.appId === undefined ? null : { appId: v.appId }),
            };
        });
}

/** @internal */
export namespace UpdateAppResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Application?: components.Application$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateAppResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Application: components.Application$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Application === undefined ? null : { application: v.Application }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Application?: components.Application$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateAppResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            application: components.Application$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.application === undefined ? null : { Application: v.application }),
            };
        });
}
