/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Region, Region$ } from "./region";
import * as z from "zod";

export type CreatePrivateLobbyDeprecatedSecurity = {
    playerAuth: string;
};

export type CreatePrivateLobbyDeprecatedRequest = {
    appId?: string | undefined;
    local?: boolean | undefined;
    region?: Region | undefined;
};

export type CreatePrivateLobbyDeprecatedResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Ok
     */
    roomId?: string | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreatePrivateLobbyDeprecatedSecurity$ {
    export type Inbound = {
        playerAuth: string;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedSecurity,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            playerAuth: z.string(),
        })
        .transform((v) => {
            return {
                playerAuth: v.playerAuth,
            };
        });

    export type Outbound = {
        playerAuth: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedSecurity
    > = z
        .object({
            playerAuth: z.string(),
        })
        .transform((v) => {
            return {
                playerAuth: v.playerAuth,
            };
        });
}

/** @internal */
export namespace CreatePrivateLobbyDeprecatedRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        local?: boolean | undefined;
        region?: Region | undefined;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            appId: z.string().optional(),
            local: z.boolean().default(false),
            region: Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                local: v.local,
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        local: boolean;
        region?: Region | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedRequest
    > = z
        .object({
            appId: z.string().optional(),
            local: z.boolean().default(false),
            region: Region$.optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                local: v.local,
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });
}

/** @internal */
export namespace CreatePrivateLobbyDeprecatedResponse$ {
    export type Inbound = {
        ContentType: string;
        RoomId?: string | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<
        CreatePrivateLobbyDeprecatedResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            ContentType: z.string(),
            RoomId: z.string().optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.RoomId === undefined ? null : { roomId: v.RoomId }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        RoomId?: string | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreatePrivateLobbyDeprecatedResponse
    > = z
        .object({
            contentType: z.string(),
            roomId: z.string().optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.roomId === undefined ? null : { RoomId: v.roomId }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
