/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OrgToken, OrgToken$ } from "./orgtoken";
import * as z from "zod";

export type CreatedOrgToken = {
    orgToken: OrgToken;
    plainTextToken: string;
};

/** @internal */
export namespace CreatedOrgToken$ {
    export type Inbound = {
        orgToken: OrgToken$.Inbound;
        plainTextToken: string;
    };

    export const inboundSchema: z.ZodType<CreatedOrgToken, z.ZodTypeDef, Inbound> = z
        .object({
            orgToken: OrgToken$.inboundSchema,
            plainTextToken: z.string(),
        })
        .transform((v) => {
            return {
                orgToken: v.orgToken,
                plainTextToken: v.plainTextToken,
            };
        });

    export type Outbound = {
        orgToken: OrgToken$.Outbound;
        plainTextToken: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreatedOrgToken> = z
        .object({
            orgToken: OrgToken$.outboundSchema,
            plainTextToken: z.string(),
        })
        .transform((v) => {
            return {
                orgToken: v.orgToken,
                plainTextToken: v.plainTextToken,
            };
        });
}
