/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetLogsForProcessRequest = {
    appId?: string | undefined;
    follow?: boolean | undefined;
    processId: string;
    tailLines?: number | undefined;
};

export type GetLogsForProcessResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Ok
     */
    res?: string | undefined;
};

/** @internal */
export namespace GetLogsForProcessRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        follow?: boolean | undefined;
        processId: string;
        tailLines?: number | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForProcessRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            processId: z.string(),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                processId: v.processId,
                tailLines: v.tailLines,
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        follow: boolean;
        processId: string;
        tailLines: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForProcessRequest> = z
        .object({
            appId: z.string().optional(),
            follow: z.boolean().default(false),
            processId: z.string(),
            tailLines: z.number().int().default(100),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                follow: v.follow,
                processId: v.processId,
                tailLines: v.tailLines,
            };
        });
}

/** @internal */
export namespace GetLogsForProcessResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        res?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetLogsForProcessResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            res: z.string().optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        res?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLogsForProcessResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            res: z.string().optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.res === undefined ? null : { res: v.res }),
            };
        });
}
