/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ProcessStatus, ProcessStatus$ } from "./processstatus";
import { ProcessV2, ProcessV2$ } from "./processv2";
import { Region, Region$ } from "./region";
import * as z from "zod";

export type GetLatestProcessesRequest = {
    appId?: string | undefined;
    region?: Array<Region> | undefined;
    status?: Array<ProcessStatus> | undefined;
};

export type GetLatestProcessesResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Ok
     */
    classes?: Array<ProcessV2> | undefined;
};

/** @internal */
export namespace GetLatestProcessesRequest$ {
    export type Inbound = {
        appId?: string | undefined;
        region?: Array<Region> | undefined;
        status?: Array<ProcessStatus> | undefined;
    };

    export const inboundSchema: z.ZodType<GetLatestProcessesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            appId: z.string().optional(),
            region: z.array(Region$).optional(),
            status: z.array(ProcessStatus$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });

    export type Outbound = {
        appId?: string | undefined;
        region?: Array<Region> | undefined;
        status?: Array<ProcessStatus> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLatestProcessesRequest> = z
        .object({
            appId: z.string().optional(),
            region: z.array(Region$).optional(),
            status: z.array(ProcessStatus$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.appId === undefined ? null : { appId: v.appId }),
                ...(v.region === undefined ? null : { region: v.region }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });
}

/** @internal */
export namespace GetLatestProcessesResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        classes?: Array<ProcessV2$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<GetLatestProcessesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            classes: z.array(ProcessV2$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.classes === undefined ? null : { classes: v.classes }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        classes?: Array<ProcessV2$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLatestProcessesResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            classes: z.array(ProcessV2$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.classes === undefined ? null : { classes: v.classes }),
            };
        });
}
