/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ExposedPort, ExposedPort$ } from "./exposedport";
import { ProcessStatus, ProcessStatus$ } from "./processstatus";
import { Region, Region$ } from "./region";
import { TransportType, TransportType$ } from "./transporttype";
import * as z from "zod";

/**
 * Connection details for an active process.
 */
export type ProcessV2ExposedPort = {
    host: string;
    name: string;
    port: number;
    /**
     * Transport type specifies the underlying communication protocol to the exposed port.
     */
    transportType: TransportType;
};

export type ProcessV2 = {
    additionalExposedPorts: Array<ExposedPort>;
    /**
     * System generated unique identifier for an application.
     */
    appId: string;
    /**
     * When the process started being provisioned.
     */
    createdAt: Date;
    /**
     * System generated id for a deployment. Increments by 1.
     */
    deploymentId: number;
    exposedPort: ProcessV2ExposedPort | null;
    /**
     * System generated unique identifier to a runtime instance of your game server.
     */
    processId: string;
    region: Region;
    /**
     * Tracks the number of rooms that have been allocated to the process.
     */
    roomsAllocated: number;
    /**
     * Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
     */
    roomsPerProcess: number;
    /**
     * When the process bound to the specified port. We use this to determine when we should start billing.
     */
    startedAt: Date | null;
    status: ProcessStatus;
    /**
     * When the process is issued to stop. We use this to determine when we should stop billing.
     */
    stoppingAt: Date | null;
    /**
     * When the process has been terminated.
     */
    terminatedAt: Date | null;
};

/** @internal */
export namespace ProcessV2ExposedPort$ {
    export type Inbound = {
        host: string;
        name: string;
        port: number;
        transportType: TransportType;
    };

    export const inboundSchema: z.ZodType<ProcessV2ExposedPort, z.ZodTypeDef, Inbound> = z
        .object({
            host: z.string(),
            name: z.string(),
            port: z.number().int(),
            transportType: TransportType$,
        })
        .transform((v) => {
            return {
                host: v.host,
                name: v.name,
                port: v.port,
                transportType: v.transportType,
            };
        });

    export type Outbound = {
        host: string;
        name: string;
        port: number;
        transportType: TransportType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProcessV2ExposedPort> = z
        .object({
            host: z.string(),
            name: z.string(),
            port: z.number().int(),
            transportType: TransportType$,
        })
        .transform((v) => {
            return {
                host: v.host,
                name: v.name,
                port: v.port,
                transportType: v.transportType,
            };
        });
}

/** @internal */
export namespace ProcessV2$ {
    export type Inbound = {
        additionalExposedPorts: Array<ExposedPort$.Inbound>;
        appId: string;
        createdAt: string;
        deploymentId: number;
        exposedPort: ProcessV2ExposedPort$.Inbound | null;
        processId: string;
        region: Region;
        roomsAllocated: number;
        roomsPerProcess: number;
        startedAt: string | null;
        status: ProcessStatus;
        stoppingAt: string | null;
        terminatedAt: string | null;
    };

    export const inboundSchema: z.ZodType<ProcessV2, z.ZodTypeDef, Inbound> = z
        .object({
            additionalExposedPorts: z.array(ExposedPort$.inboundSchema),
            appId: z.string(),
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            deploymentId: z.number().int(),
            exposedPort: z.nullable(z.lazy(() => ProcessV2ExposedPort$.inboundSchema)),
            processId: z.string(),
            region: Region$,
            roomsAllocated: z.number().int(),
            roomsPerProcess: z.number().int(),
            startedAt: z.nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            ),
            status: ProcessStatus$,
            stoppingAt: z.nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            ),
            terminatedAt: z.nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            ),
        })
        .transform((v) => {
            return {
                additionalExposedPorts: v.additionalExposedPorts,
                appId: v.appId,
                createdAt: v.createdAt,
                deploymentId: v.deploymentId,
                exposedPort: v.exposedPort,
                processId: v.processId,
                region: v.region,
                roomsAllocated: v.roomsAllocated,
                roomsPerProcess: v.roomsPerProcess,
                startedAt: v.startedAt,
                status: v.status,
                stoppingAt: v.stoppingAt,
                terminatedAt: v.terminatedAt,
            };
        });

    export type Outbound = {
        additionalExposedPorts: Array<ExposedPort$.Outbound>;
        appId: string;
        createdAt: string;
        deploymentId: number;
        exposedPort: ProcessV2ExposedPort$.Outbound | null;
        processId: string;
        region: Region;
        roomsAllocated: number;
        roomsPerProcess: number;
        startedAt: string | null;
        status: ProcessStatus;
        stoppingAt: string | null;
        terminatedAt: string | null;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProcessV2> = z
        .object({
            additionalExposedPorts: z.array(ExposedPort$.outboundSchema),
            appId: z.string(),
            createdAt: z.date().transform((v) => v.toISOString()),
            deploymentId: z.number().int(),
            exposedPort: z.nullable(z.lazy(() => ProcessV2ExposedPort$.outboundSchema)),
            processId: z.string(),
            region: Region$,
            roomsAllocated: z.number().int(),
            roomsPerProcess: z.number().int(),
            startedAt: z.nullable(z.date().transform((v) => v.toISOString())),
            status: ProcessStatus$,
            stoppingAt: z.nullable(z.date().transform((v) => v.toISOString())),
            terminatedAt: z.nullable(z.date().transform((v) => v.toISOString())),
        })
        .transform((v) => {
            return {
                additionalExposedPorts: v.additionalExposedPorts,
                appId: v.appId,
                createdAt: v.createdAt,
                deploymentId: v.deploymentId,
                exposedPort: v.exposedPort,
                processId: v.processId,
                region: v.region,
                roomsAllocated: v.roomsAllocated,
                roomsPerProcess: v.roomsPerProcess,
                startedAt: v.startedAt,
                status: v.status,
                stoppingAt: v.stoppingAt,
                terminatedAt: v.terminatedAt,
            };
        });
}
