/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type RevokeOrgTokenRequest = {
    orgId: string;
    orgTokenId: string;
};

export type RevokeOrgTokenResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Ok
     */
    boolean?: boolean | undefined;
};

/** @internal */
export namespace RevokeOrgTokenRequest$ {
    export type Inbound = {
        orgId: string;
        orgTokenId: string;
    };

    export const inboundSchema: z.ZodType<RevokeOrgTokenRequest, z.ZodTypeDef, Inbound> = z
        .object({
            orgId: z.string(),
            orgTokenId: z.string(),
        })
        .transform((v) => {
            return {
                orgId: v.orgId,
                orgTokenId: v.orgTokenId,
            };
        });

    export type Outbound = {
        orgId: string;
        orgTokenId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RevokeOrgTokenRequest> = z
        .object({
            orgId: z.string(),
            orgTokenId: z.string(),
        })
        .transform((v) => {
            return {
                orgId: v.orgId,
                orgTokenId: v.orgTokenId,
            };
        });
}

/** @internal */
export namespace RevokeOrgTokenResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        boolean?: boolean | undefined;
    };

    export const inboundSchema: z.ZodType<RevokeOrgTokenResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            boolean: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.boolean === undefined ? null : { boolean: v.boolean }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        boolean?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RevokeOrgTokenResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            boolean: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.boolean === undefined ? null : { boolean: v.boolean }),
            };
        });
}
