workflowVersion: 1.0.0
sources:
    openapi:
        inputs:
            - location: https://hathora.dev/swagger.json
targets:
    java-target:
        target: java
        source: openapi
        codeSamples:
            output: codeSamples.yaml
        output: java
    typescript-target:
        target: typescript
        source: openapi
        codeSamples:
            output: codeSamples.yaml
        output: ts
    unity-target:
        target: unity
        source: openapi
        codeSamples:
            output: codeSamples.yaml
        output: unity